login_redirection:
  anonymous: null
  authenticated: /civicrm/user
  content_editor: /admin/config/cilb-admin-dashboard
  administrator: /admin/config/cilb-admin-dashboard
  candidate: /civicrm/user
  staff: /admin/config/cilb-admin-dashboard
exclude_urls: ''
